# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 23:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choece_text',
            new_name='choice_text',
        ),
    ]
